package org.swing.productV3.form;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

public class MainForm extends JFrame {
    public JPanel mainPanel;
    public JPanel centerPanel;
    public JPanel northPanel;
    public JPanel listPanel;
    public JPanel tablePanel;
    public JScrollPane scrollTable;
    public JTable table;
    public JScrollPane scrollList;
    public JList jListComp;
    public JPanel southPanel;
    public JButton addProdBtn;
    public JButton deleteProdBtn;
    public JButton addCompBtn;
    public JButton deleteCompBtn;

    public JMenuItem menuLoad = new JMenuItem("Загрузить");
    public JMenuItem menuExit = new JMenuItem("Выход");
    public JMenuItem menuGuide = new JMenuItem("Просмотреть справку");
    public JMenuItem menuReport = new JMenuItem("Отправить отзыв");
    public JMenuItem menuInfo = new JMenuItem("О программе");
    public JMenuItem menuSearch = new JMenuItem("Искать");

    public MainForm() {
        super("Проект Y");
        setContentPane(mainPanel);
        JMenuBar mb = new JMenuBar();
        JMenu m1 = new JMenu("Операции");
        JMenu m2 = new JMenu("Справка");
        mb.add(m1);
        mb.add(m2);

        m1.add(menuLoad);
        m1.add(menuSearch);
        m1.add(menuExit);

        m2.add(menuGuide);
        m2.add(menuReport);
        m2.add(menuInfo);

        mainPanel.add(BorderLayout.NORTH, mb);

        addCompBtn.setEnabled(false);
        addProdBtn.setEnabled(false);
        deleteProdBtn.setEnabled(false);
        deleteCompBtn.setEnabled(false);

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setSize(400, 400);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        northPanel = new JPanel();
        northPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(northPanel, BorderLayout.NORTH);
        centerPanel = new JPanel();
        centerPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(centerPanel, BorderLayout.CENTER);
        tablePanel = new JPanel();
        tablePanel.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        centerPanel.add(tablePanel, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        scrollTable = new JScrollPane();
        tablePanel.add(scrollTable, new GridConstraints(0, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        table = new JTable();
        scrollTable.setViewportView(table);
        addProdBtn = new JButton();
        addProdBtn.setText("Add");
        tablePanel.add(addProdBtn, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        deleteProdBtn = new JButton();
        deleteProdBtn.setText("Delete");
        tablePanel.add(deleteProdBtn, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        listPanel = new JPanel();
        listPanel.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        centerPanel.add(listPanel, new GridConstraints(0, 0, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        scrollList = new JScrollPane();
        listPanel.add(scrollList, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        jListComp = new JList();
        scrollList.setViewportView(jListComp);
        addCompBtn = new JButton();
        addCompBtn.setHorizontalAlignment(0);
        addCompBtn.setText("Add");
        listPanel.add(addCompBtn, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        deleteCompBtn = new JButton();
        deleteCompBtn.setText("Delete");
        listPanel.add(deleteCompBtn, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        southPanel = new JPanel();
        southPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(southPanel, BorderLayout.SOUTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}